apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-configmap
  namespace: api
data:
  PRISMA_CONFIG: |
    port: 4466
    # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
    # managementApiSecret: my-secret
    databases:
      default:
        connector: postgres
        host: examreg.c0mlsytycbjb.ap-southeast-1.rds.amazonaws.com
        database: examreg
        user: postgres
        password: postgres
        rawAccess: true
        port: 5432
        migrations: true
